apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pleesah-game
  namespace: leesah
spec:
  accessPolicy:
    outbound:
      rules:
        - application: pleesah-havnesjef
  port: 3000
  ingresses:
    - "https://leesah.io/kubernetes"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "10m"
      memory: 128Mi
  env:
    - name: VITE_API_URL
      value: http://pleesah-havnesjef
    - name: VITE_API_PATH
      value: /kubernetes/api
